Update CMake build system for EMC TC_tracker
NOAA-EMC/TC_tracker pull request #9
Opened 2024-12-30 20:01 UTC by HananehJafary-NOAA

This PR also suggests fixes for issue #3

2025-01-03 19:14 UTC, DavidHuber-NOAA commented on modulefiles/hercules.lua
> +setenv("CMAKE_Platform", "jet.intel")
I think this should be hercules.intel.

2025-01-03 19:14 UTC, DavidHuber-NOAA commented on modulefiles/orion.lua
> +setenv("CMAKE_Platform", "jet.intel")
Orion.

2025-01-03 19:20 UTC, DavidHuber-NOAA commented on sorc/machine-setup.sh
> +    module use /apps/contrib/NCEPLIBS/orion/modulefiles
Determining if you are on Orion or Hercules can be tricky.  Here is a method we have used that works pretty well:

```bash
elif [[ -d /work2/noaa ]]; then
  # We are on MSU Orion or Hercules
  mount=$(findmnt -n -o SOURCE /home)
  if [[ ${mount} =~ "hercules" ]]; then
    MACHINE_ID=hercules
  else
    MACHINE_ID=orion
  fi
```

2025-01-08 06:10 UTC, HananehJafary-NOAA commented on sorc/machine-setup.sh
> +    module use /apps/contrib/NCEPLIBS/orion/modulefiles
Thank you for the comments. I have edited all the suggestions and tested again in all the machines.

2025-01-13 16:49 UTC, KateFriedman-NOAA requested changes
These are massive updates, thank you for making them @HananehJafary-NOAA ! I left a series of comments to address. Please let me know what questions you may have or guidance you may need to address them. Thanks!

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on control/hera/jfv3_cyclone_genesis_00.ecf_hera
> +module use /scratch2/NCEPDEV/ovp/Hana.Jafary/test_fix_cmake/modulefiles
Consider replacing the personal hardcoded paths with a path that's relative to the clone location, so it can find the `modulefiles/` path every time.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on control/hera/jfv3_cyclone_genesis_00.ecf_hera
> +VERSION_FILE=${NWROOT}/Input/versions/tracker.ver
What version file is this? Current implementation/NCO standards require a versions folder at the top level with version files (.ver) inside. I see that build.ver and run.ver are deleted in this PR...you'll need to add those back with the defaults for WCOSS2. You can then create additional .ver files to support the R&D machines. I can provide guidance on that if you would like it.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on ecf/jgfs_tc_genesis.ecf
> +export KEEPDATA=YES
Will this script be used in operations for this package? If so, remove the hardcoded path settings. Here is an example ecf script from the GFS package, for guidance on making ecf scripts for operations: https://github.com/NOAA-EMC/global-workflow/blob/dev/gfs.v16/ecf/scripts/gfs/jgfs_forecast.ecf

1. All modules are loading individually in the ecf scripts and do not load the modulefiles.
2. `HOMEens_tracker`, `COMROOT`, and `DATAROOT` should already be set by the ecflow manager. Can remove.
3. Can remove `clustername` since it's not needed for module loading in this ecf script.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on ecf/jgfs_tc_track_avno.ecf
> +export KEEPDATA=YES
See related comment in other ecf script.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on jobs/JFV3_CYCLONE_GENESIS_JP
> +  export COMINgfs=${COMINgfs:-/scratch2/NCEPDEV/ovp/Hana.Jafary/Input/gfs.${PDY}}
This comment applies to lines 61 through 98. Consider compressing these lines into a single block that sets the various paths you need but accepts overrides from outside for use outside of operations. Set things like `COMINsyn` and `COMINgfs` with the default that ops will use but have the override variables to set from outside for testing outside of ops. I can provide guidance if helpful, let me know. Essentially, you want the scripts from the JJOB level downward to function for operations but accept overrides where needed for testing outside of ops. No hardcoded personal paths, including no machine if-blocks.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on jobs/JFV3_CYCLONE_TRACK_JP
> +  export COMINgfs=${COMINgfs:-/scratch2/NCEPDEV/ovp/Hana.Jafary/Input/gfs.${PDY}}
Similar comment about removing machine-specific if-blocks and hardcoded personal paths. Make generic for ops but allow overrides for testing.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on jobs/JGFS_TC_GENESIS
> +#export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}
Can remove this line and any other instances of `jlogfile`. The `jlogfile` has been retired from operational use.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on jobs/JGFS_TC_GENESIS
> +export HOMEens_tracker=${HOMEens_tracker:-${NWROOT:?}}
Check instances of `HOMEens_tracker` being set. You should set it like this:
```
export HOMEens_tracker=${HOMEens_tracker:${PACKAGEROOT}/ens_tracker.${ens_tracker_ver}}
```
Example from the GFS:
```
export HOMEgfs=${HOMEgfs:-${PACKAGEROOT}/gfs.${gfs_ver}}
```
The `NWROOT` variable has been replaced with `PACKAGEROOT` in operations on WCOSS2. It's defined as `/lfs/h1/ops/prod/packages` by operations.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on jobs/JGFS_TC_GENESIS
> +#export COMOUTgenvit=${COMOUTgenvit:-${GESROOT:?}/${envir}/${NET}/genesis_vital_${JYYYY}}
Remove commented out lines. Set test values outside of script as needed, otherwise make sure these are set for operational use.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on jobs/JGFS_TC_TRACK_AVNO
> +#export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}
Can remove.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on jobs/JGFS_TC_TRACK_AVNO
> -#export RUN=${RUN:-gfs}
Remove.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on jobs/JGFS_TC_TRACK_AVNO
> +export SENDDBN=${SENDDBN:-NO}
Set defaults for operational use (most likely "YES", double check) and send in overrides as needed for testing.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on jobs/JGFS_TC_TRACK_AVNO
> +export HOMEens_tracker=${HOMEens_tracker:-${NWROOT:?}}
See earlier comment about `HOMEens_tracker`.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on jobs/JGFS_TC_TRACK_AVNO
> +
Remove commented out personal paths.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on modulefiles/hera.lua
> +loads hafs_tracker modulefile and related set environment veriables on Hera
Double check comments in modulefiles to make sure they are accurate for the package name and machine.

2025-01-13 16:49 UTC, KateFriedman-NOAA commented on sorc/machine-setup.sh
> +target=""
Consider using the `target` variable elsewhere in package instead of `clustername`, for consistency.

2025-02-20 23:37 UTC, HananehJafary-NOAA commented on ecf/jgfs_tc_genesis.ecf
> +export KEEPDATA=YES
Will add these changes to the operational package.

2025-02-20 23:39 UTC, HananehJafary-NOAA commented on control/hera/jfv3_cyclone_genesis_00.ecf_hera
> +VERSION_FILE=${NWROOT}/Input/versions/tracker.ver
I will incorporate the version file once our packages are merged.

2025-02-21 16:08 UTC, KateFriedman-NOAA requested changes
Looks good, just a few remaining edits to make. Thanks!

2025-02-21 16:08 UTC, KateFriedman-NOAA commented on jobs/JGFS_TC_GENESIS
> +#export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}
Don't forget to remove this jlogfile line, thanks!

2025-02-21 16:08 UTC, KateFriedman-NOAA commented on jobs/JFV3_CYCLONE_GENESIS_JP
> +export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEROOT:?}/TC_tracker.${TC_tracker_ver}}
Apologies, I think I misunderstood one of your questions during our chat this week. This can stay as `ens_tracker`, you just needed to add the bit after `PACKAGEROOT` in. This will help with merging with the ens_tracker repo.
```suggestion
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEROOT:?}/ens_tracker.${ens_tracker_ver}}
```

2025-02-21 16:08 UTC, KateFriedman-NOAA commented on jobs/JFV3_CYCLONE_TRACK_JP
> +export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEROOT:?}/TC_tracker.${TC_tracker_ver}}
```suggestion
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEROOT:?}/ens_tracker.${ens_tracker_ver}}
```

2025-02-21 16:54 UTC, DavidHuber-NOAA approved these changes
I don't have any suggestions beyond Kate's for this PR, though I do have some suggestions for simplifying some of the machine blocks for a future PR.  Approve pending the addressing of Kate's comments.

2025-02-21 16:54 UTC, DavidHuber-NOAA commented on control/hera/jfv3_cyclone_genesis_00.ecf_hera
> +module load ${target}.lua
I learned something new here.  I didn't realize you could specify that the file was .lua in a module load.

2025-02-21 16:54 UTC, DavidHuber-NOAA commented on jobs/JFV3_CYCLONE_GENESIS_JP
>    # We are on MSU Orion
This could be either Orion or Hercules.  This is a technicality in this case, but in some cases it does matter.  If you need to know when one you are on, you can use this trick:

```
  # We are on MSU Orion or Hercules
  mount=$(findmnt -n -o SOURCE /home)
  if [[ ${mount} =~ "hercules" ]]; then
    MACHINE_ID=hercules
  else
    MACHINE_ID=orion
  fi
```

Also, it may be useful at some point (not for this PR) to develop a `detect_machine.sh` script that is sourced everywhere that needs it.  This will save having to edit these kinds of things across multiple scripts.  See, for example, https://github.com/NOAA-EMC/gfs-utils/blob/develop/ush/detect_machine.sh.

2025-02-21 16:54 UTC, DavidHuber-NOAA commented on modulefiles/gaeac6.lua
> +load(pathJoin("craype", craype_ver))
I suggest in a later PR that you keep a list of versions in a version file since they are (generally) common to spack-stack versions

2025-02-21 16:54 UTC, DavidHuber-NOAA commented on sorc/build_tracker.sh
> +make -j 8 VERBOSE=2
Again, another time, but it may be useful to have BUILD_JOBS and VERBOSE options set as variables similar to BUILD_MODE above so the user can specify how verbose they want it to build.

2025-02-21 18:29 UTC, HananehJafary-NOAA commented
Thank you so much for all your comments!!!

2025-02-21 18:30 UTC, merged